import os
import re
import math
from pathlib import Path
from typing import List, Dict, Any, Optional
from app.schemas.transcript import DialogueSegment
from app.config import settings

def format_ass_time(seconds: float) -> str:
    """Chuyển đổi giây sang định dạng ASS H:MM:SS.CC."""
    if seconds < 0:
        seconds = 0.0
    hrs = int(seconds // 3600)
    mins = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    centis = int(round((seconds - int(seconds)) * 100))
    if centis >= 100:
        centis = 99
    return f"{hrs}:{mins:02d}:{secs:02d}.{centis:02d}"

class KaraokeSubtitleService:
    @staticmethod
    def generate_word_karaoke_tags(viet_text: str, duration_sec: float) -> str:
        """
        Phân bổ thời lượng phát âm từng từ dựa trên số lượng ký tự và âm tiết,
        tạo thẻ karaoke {\\kf<centiseconds>} sáng chữ mượt mà chuẩn từng mili-giây.
        """
        words = viet_text.strip().split()
        if not words:
            return ""

        total_chars = sum(len(w) for w in words)
        total_cs = max(int(duration_sec * 100), len(words) * 10)  # 1s = 100 centiseconds

        karaoke_parts = []
        accumulated_cs = 0

        for i, w in enumerate(words):
            if i == len(words) - 1:
                w_cs = max(total_cs - accumulated_cs, 10)
            else:
                weight = len(w) / max(total_chars, 1)
                w_cs = max(int(round(total_cs * weight)), 10)
                accumulated_cs += w_cs

            karaoke_parts.append(f"{{\\kf{w_cs}}}{w}")

        return " ".join(karaoke_parts)

    @classmethod
    def create_karaoke_ass_file(
        cls,
        segments: List[DialogueSegment],
        output_ass_path: str,
        video_title: str = "Video Review",
        width: int = 1920,
        height: int = 1080,
        font_name: str = "Arial",
        font_size: int = 14,
        primary_color: Optional[str] = None,
        highlight_color: Optional[str] = None,
        outline_color: Optional[str] = None,
        backdrop_opacity_hex: str = "80",       # Hộp nền mờ 50% opacity
        margin_v: int = 10,                     # Cao độ phụ đề từ đáy (px)
        box_style: str = "white_box",           # "white_box" (Khung Trắng bo tròn chữ Đen), "dark_box" (Hộp Đen mờ), "outline_only" (Chữ viền nổi)
        box_padding: int = 8                    # Độ to theo chiều dọc / padding của hộp che chữ gốc (px)
    ) -> str:
        """
        Tạo file phụ đề ASS Karaoke chuyên nghiệp:
        - Kiểu A (Mặc định: 'white_box'): Khung viền Trắng bo tròn che sạch chữ gốc, chữ Đen đậm + Karaoke Xanh hoàng gia.
        - Kiểu B ('dark_box'): Hộp Đen mờ bo góc sang trọng + Chữ Trắng / Highlight Vàng kim.
        - Kiểu C ('outline_only'): Chữ viền hairline trong suốt không nền.
        - box_padding: Điều chỉnh độ to theo chiều dọc của hộp che để phủ kín hoàn toàn phụ đề tiếng Trung cũ.
        """
        style_mode = (box_style or "white_box").lower()

        if style_mode == "white_box":
            # ⚪ KIỂU A: KHUNG TRẮNG BO TRÒN - CHỮ ĐEN ĐẬM / HIGHLIGHT XANH HOÀNG GIA (Che chữ gốc 100%)
            border_style = 3  # 3 = Opaque Box (Hộp nền bao quanh chữ)
            outline_val = max(3.0, float(box_padding if box_padding is not None else 8.0))
            shadow_val = 1.0  # Bóng nhẹ cho hộp nền nổi khối
            primary_c = primary_color or "&H00111111"       # Chữ Đen than chì siêu đậm & sắc nét
            highlight_c = highlight_color or "&H00EB6325"   # Karaoke Xanh hoàng gia Electric Blue (&HAABBGGRR: #2563EB)
            outline_c = outline_color or "&H00D0D5DD"       # Viền bo xám nhẹ tinh tế viền quanh hộp trắng
            back_c = "&H00FFFFFF"                           # Nền trắng tinh khiết che phủ hoàn toàn chữ gốc
            bold_val = 1                                    # Chữ in đậm rõ ràng

        elif style_mode == "dark_box":
            # ⚫ KIỂU B: HỘP ĐEN MỜ BO GÓC - CHỮ TRẮNG / HIGHLIGHT VÀNG KIM ĐIỆN ẢNH
            border_style = 3
            outline_val = max(3.0, float(box_padding if box_padding is not None else 8.0))
            shadow_val = 1.0
            primary_c = primary_color or "&H00FFFFFF"
            highlight_c = highlight_color or "&H0000D7FF"   # Vàng kim sang trọng
            outline_c = outline_color or "&H00333333"
            back_c = f"&H{backdrop_opacity_hex}000000"
            bold_val = 1

        else:
            # 🔤 KIỂU C: CHỮ VIỀN NỔI HAIRLINE TRONG SUỐT (Không hộp che)
            border_style = 1
            outline_val = max(0.8, round(font_size * 0.075, 1))
            shadow_val = max(0.4, round(font_size * 0.035, 1))
            primary_c = primary_color or "&H00FFFFFF"
            highlight_c = highlight_color or "&H0000D7FF"
            outline_c = outline_color or "&H00000000"
            back_c = "&H00000000"
            bold_val = 0

        ass_header = f"""[Script Info]
; Script generated by ReviewMatThon Ultra Karaoke Engine
Title: {video_title}
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
PlayResX: {width}
PlayResY: {height}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
; Style Karaoke: BorderStyle={border_style}, Outline={outline_val}, Bold={bold_val}, MarginV={margin_v}
Style: KaraokeSub,{font_name},{font_size},{primary_c},{highlight_c},{outline_c},{back_c},{bold_val},0,0,0,100,100,0,0,{border_style},{outline_val},{shadow_val},2,15,15,{margin_v},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
        events = []
        for s in segments:
            text = (getattr(s, 'translated_text', '') or s.clean_text or s.text or "").strip()
            # Xóa sạch 100% số thứ tự đầu câu (1. , 02. , [1], Câu 1:...)
            text = re.sub(r'^(?:\[\s*\d+\s*\]|\(\s*\d+\s*\)|\{\s*\d+\s*\}|【\s*\d+\s*】)\s*[\.\:\-\–\—\s]*', '', text)
            text = re.sub(r'^(?:câu|thoại|đoạn|stt|dòng|line)\s*\d+\s*[\.\:\-\–\—\)\/\]\s]*\s*', '', text, flags=re.IGNORECASE)
            text = re.sub(r'^\d+\/\d+\s*[\.\:\-\–\—\s]*', '', text)
            text = re.sub(r'^\d+\s*[\.\:\-\–\—\)\/\]]+\s*', '', text)
            text = re.sub(r'^[^\w\s\(\[\{]+', '', text).strip()
            if not text:
                continue

            effective_end = max(s.end, s.start + 0.3)
            start_ts = format_ass_time(s.start)
            end_ts = format_ass_time(effective_end)
            dur = max(effective_end - s.start, 0.5)

            karaoke_text = cls.generate_word_karaoke_tags(text, dur)
            line = f"Dialogue: 0,{start_ts},{end_ts},KaraokeSub,,0,0,0,,{karaoke_text}"
            events.append(line)

        full_ass_content = ass_header + "\n".join(events) + "\n"

        out_path = Path(output_ass_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(full_ass_content)

        return str(out_path)
