import os
import re
import math
from pathlib import Path
from typing import List, Dict, Any, Optional
from app.schemas.transcript import DialogueSegment
from app.config import settings

def format_ass_time(seconds: float) -> str:
    """Chuyển đổi giây sang định dạng ASS H:MM:SS.CC."""
    if seconds < 0:
        seconds = 0.0
    hrs = int(seconds // 3600)
    mins = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    centis = int(round((seconds - int(seconds)) * 100))
    if centis >= 100:
        centis = 99
    return f"{hrs}:{mins:02d}:{secs:02d}.{centis:02d}"

class KaraokeSubtitleService:
    @staticmethod
    def generate_word_karaoke_tags(viet_text: str, duration_sec: float) -> str:
        """
        Phân bổ thời lượng phát âm từng từ dựa trên số lượng ký tự và âm tiết,
        tạo thẻ karaoke {\\kf<centiseconds>} sáng chữ mượt mà chuẩn từng mili-giây.
        """
        words = viet_text.strip().split()
        if not words:
            return ""

        total_chars = sum(len(w) for w in words)
        total_cs = max(int(duration_sec * 100), len(words) * 10)  # 1s = 100 centiseconds

        karaoke_parts = []
        accumulated_cs = 0

        for i, w in enumerate(words):
            if i == len(words) - 1:
                w_cs = max(total_cs - accumulated_cs, 10)
            else:
                weight = len(w) / max(total_chars, 1)
                w_cs = max(int(round(total_cs * weight)), 10)
                accumulated_cs += w_cs

            karaoke_parts.append(f"{{\\kf{w_cs}}}{w}")

        return " ".join(karaoke_parts)

    @classmethod
    def create_karaoke_ass_file(
        cls,
        segments: List[DialogueSegment],
        output_ass_path: str,
        video_title: str = "Video Review",
        width: int = 1920,
        height: int = 1080,
        font_name: str = "Arial",
        font_size: int = 40,
        primary_color: str = "&H00FFFFFF",      # Trắng tinh khiết
        highlight_color: str = "&H0000D7FF",    # Vàng kim sang trọng (&HAABBGGRR)
        outline_color: str = "&H00000000",      # Viền đen
        backdrop_opacity_hex: str = "80",       # Hộp nền mờ 50% opacity che chữ cũ
        margin_v: int = 65                      # Cao độ phụ đề từ mép dưới màn hình (px)
    ) -> str:
        """
        Tạo file phụ đề ASS Karaoke chuyên nghiệp:
        - Hiệu ứng sáng chữ từng từ (Word-by-word Highlight).
        - Hộp nền mờ thanh mảnh (Slim Frosted Backdrop) che khéo phụ đề tiếng Trung cũ.
        - Chuẩn xác từng mili-giây với file MP3 tiếng Việt.
        """
        ass_header = f"""[Script Info]
; Script generated by ReviewMatThon Ultra Karaoke Engine
Title: {video_title}
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
PlayResX: {width}
PlayResY: {height}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
; Style Karaoke: Primary = màu thường (Trắng), Secondary = màu highlight (Vàng kim), Outline = Viền đen sắc nét
Style: KaraokeSub,{font_name},{font_size},{primary_color},{highlight_color},{outline_color},&H00000000,-1,0,0,0,100,100,0,0,1,3.2,1.5,2,40,40,{margin_v},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
        events = []
        for s in segments:
            text = (getattr(s, 'translated_text', '') or s.clean_text or s.text or "").strip()
            if not text:
                continue

            start_ts = format_ass_time(s.start)
            end_ts = format_ass_time(s.end)
            dur = max(s.end - s.start, 0.5)

            karaoke_text = cls.generate_word_karaoke_tags(text, dur)
            line = f"Dialogue: 0,{start_ts},{end_ts},KaraokeSub,,0,0,0,,{karaoke_text}"
            events.append(line)

        full_ass_content = ass_header + "\n".join(events) + "\n"

        out_path = Path(output_ass_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(full_ass_content)

        return str(out_path)
